version: '3.8'
services:
  mysql-myhelp-db-2:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_USER=sa
      - MYSQL_DATABASE=myhelp
    ports:
      - '3306:3306'
    volumes:
      - mysql-myhelp-db:/var/lib/mysql
volumes:
  mysql-myhelp-db:
    driver: local